split into six groups

diff --git a/.github/workflows/mass_archive.yml b/.github/workflows/mass_archive.yml
--- a/.github/workflows/mass_archive.yml
+++ b/.github/workflows/mass_archive.yml
@@ -19,7 +19,7 @@ jobs:
       run: |
         archival_urls=($(
           IFS=$'\n'   # Set the Internal Field Separator to newline
-          echo "${{ github.event.inputs.urls }}" | sed -n '1,20p'
+          echo "${{ github.event.inputs.urls }}" | sed -n '1,10p'
         ))
         for url in "${archival_urls[@]}"; do
           echo "Archiving given page: $url"
@@ -64,7 +64,7 @@ jobs:
       run: |
         archival_urls=($(
           IFS=$'\n'   # Set the Internal Field Separator to newline
-          echo "${{ github.event.inputs.urls }}" | sed -n '21,40p'
+          echo "${{ github.event.inputs.urls }}" | sed -n '11,20p'
         ))
         for url in "${archival_urls[@]}"; do
           echo "Archiving given page: $url"
@@ -109,7 +109,142 @@ jobs:
       run: |
         archival_urls=($(
           IFS=$'\n'   # Set the Internal Field Separator to newline
-          echo "${{ github.event.inputs.urls }}" | sed -n '41,60p'
+          echo "${{ github.event.inputs.urls }}" | sed -n '21,30p'
+        ))
+        for url in "${archival_urls[@]}"; do
+          echo "Archiving given page: $url"
+    
+          # Retry loop for the main content
+          max_retries=3
+          retry_counter=0
+          while [ $retry_counter -lt $max_retries ]; do
+            curl -sS "https://web.archive.org/save/$url" > /dev/null && break
+            ((retry_counter++))
+          done
+      
+          # Retry loop for outlinks
+          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
+            echo "Archiving outlink: $outlink"
+      
+            max_retries=3
+            retry_counter=0
+            while [ $retry_counter -lt $max_retries ]; do
+              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
+                break
+              else
+                ((retry_counter++))
+                echo "Failed to archive outlink: $outlink. Retrying..."
+              fi
+            done
+
+            sleep 8s
+          done || true  # Ignore errors in the outlink archiving process
+
+          sleep 8s
+        done
+
+  archive_fourth_batch:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Check out repository
+      uses: actions/checkout@v2
+
+    - name: Archive URLs (Third Batch)
+      run: |
+        archival_urls=($(
+          IFS=$'\n'   # Set the Internal Field Separator to newline
+          echo "${{ github.event.inputs.urls }}" | sed -n '31,40p'
+        ))
+        for url in "${archival_urls[@]}"; do
+          echo "Archiving given page: $url"
+    
+          # Retry loop for the main content
+          max_retries=3
+          retry_counter=0
+          while [ $retry_counter -lt $max_retries ]; do
+            curl -sS "https://web.archive.org/save/$url" > /dev/null && break
+            ((retry_counter++))
+          done
+      
+          # Retry loop for outlinks
+          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
+            echo "Archiving outlink: $outlink"
+      
+            max_retries=3
+            retry_counter=0
+            while [ $retry_counter -lt $max_retries ]; do
+              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
+                break
+              else
+                ((retry_counter++))
+                echo "Failed to archive outlink: $outlink. Retrying..."
+              fi
+            done
+
+            sleep 8s
+          done || true  # Ignore errors in the outlink archiving process
+
+          sleep 8s
+        done
+
+  archive_fifth_batch:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Check out repository
+      uses: actions/checkout@v2
+
+    - name: Archive URLs (Third Batch)
+      run: |
+        archival_urls=($(
+          IFS=$'\n'   # Set the Internal Field Separator to newline
+          echo "${{ github.event.inputs.urls }}" | sed -n '41,50p'
+        ))
+        for url in "${archival_urls[@]}"; do
+          echo "Archiving given page: $url"
+    
+          # Retry loop for the main content
+          max_retries=3
+          retry_counter=0
+          while [ $retry_counter -lt $max_retries ]; do
+            curl -sS "https://web.archive.org/save/$url" > /dev/null && break
+            ((retry_counter++))
+          done
+      
+          # Retry loop for outlinks
+          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
+            echo "Archiving outlink: $outlink"
+      
+            max_retries=3
+            retry_counter=0
+            while [ $retry_counter -lt $max_retries ]; do
+              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
+                break
+              else
+                ((retry_counter++))
+                echo "Failed to archive outlink: $outlink. Retrying..."
+              fi
+            done
+
+            sleep 8s
+          done || true  # Ignore errors in the outlink archiving process
+
+          sleep 8s
+        done
+
+  archive_sixth_batch:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Check out repository
+      uses: actions/checkout@v2
+
+    - name: Archive URLs (Third Batch)
+      run: |
+        archival_urls=($(
+          IFS=$'\n'   # Set the Internal Field Separator to newline
+          echo "${{ github.event.inputs.urls }}" | sed -n '51,60p'
         ))
         for url in "${archival_urls[@]}"; do
           echo "Archiving given page: $url"
