split into three batches of urls

diff --git a/.github/workflows/mass_archive.yml b/.github/workflows/mass_archive.yml
--- a/.github/workflows/mass_archive.yml
+++ b/.github/workflows/mass_archive.yml
@@ -8,17 +8,16 @@ on:
         required: true
 
 jobs:
-  archive_given_page:
+  archive_first_batch:
     runs-on: ubuntu-latest
 
     steps:
     - name: Check out repository
       uses: actions/checkout@v2
 
-    - name: Archive Given Pages
+    - name: Archive URLs (First Batch)
       run: |
-        archival_urls=(${{ github.event.inputs.urls }})
-        
+        archival_urls=(${{ github.event.inputs.urls[@0,19]}})
         for url in "${archival_urls[@]}"; do
           echo "Archiving given page: $url"
     
@@ -30,22 +29,89 @@ jobs:
             ((retry_counter++))
           done
       
+          # Retry loop for outlinks
+          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
+            echo "Archiving outlink: $outlink"
+      
+            max_retries=3
+            retry_counter=0
+            while [ $retry_counter -lt $max_retries ]; do
+              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
+                break
+              else
+                ((retry_counter++))
+                echo "Failed to archive outlink: $outlink. Retrying..."
+              fi
+            done
+
+            sleep 8s
+          done || true  # Ignore errors in the outlink archiving process
+
           sleep 8s
         done
 
-  archive_outlinks:
+  archive_second_batch:
     runs-on: ubuntu-latest
 
     steps:
     - name: Check out repository
       uses: actions/checkout@v2
 
-    - name: Archive Outlinks
+    - name: Archive URLs (Second Batch)
       run: |
-        archival_urls=(${{ github.event.inputs.urls }})
-        
+        archival_urls=(${{ github.event.inputs.urls[@20,39]}})
         for url in "${archival_urls[@]}"; do
-          echo "Archiving outlinks for page: $url"
+          echo "Archiving given page: $url"
+    
+          # Retry loop for the main content
+          max_retries=3
+          retry_counter=0
+          while [ $retry_counter -lt $max_retries ]; do
+            curl -sS "https://web.archive.org/save/$url" > /dev/null && break
+            ((retry_counter++))
+          done
+      
+          # Retry loop for outlinks
+          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
+            echo "Archiving outlink: $outlink"
+      
+            max_retries=3
+            retry_counter=0
+            while [ $retry_counter -lt $max_retries ]; do
+              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
+                break
+              else
+                ((retry_counter++))
+                echo "Failed to archive outlink: $outlink. Retrying..."
+              fi
+            done
+
+            sleep 8s
+          done || true  # Ignore errors in the outlink archiving process
+
+          sleep 8s
+        done
+
+  archive_third_batch:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Check out repository
+      uses: actions/checkout@v2
+
+    - name: Archive URLs (Third Batch)
+      run: |
+        archival_urls=(${{ github.event.inputs.urls[@40,59]}})
+        for url in "${archival_urls[@]}"; do
+          echo "Archiving given page: $url"
+    
+          # Retry loop for the main content
+          max_retries=3
+          retry_counter=0
+          while [ $retry_counter -lt $max_retries ]; do
+            curl -sS "https://web.archive.org/save/$url" > /dev/null && break
+            ((retry_counter++))
+          done
       
           # Retry loop for outlinks
           curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
