revert changes

diff --git a/.github/workflows/mass_archive.yml b/.github/workflows/mass_archive.yml
--- a/.github/workflows/mass_archive.yml
+++ b/.github/workflows/mass_archive.yml
@@ -7,38 +7,36 @@ on:
         description: 'List of URLs (separated by newlines)'
         required: true
 
-concurrency:
-  group: archive-workflow
-  cancel-in-progress: false
-
 jobs:
-  archive:
+  archive_first_batch:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Archive URLs
+    - name: Archive URLs (First Batch)
       run: |
-        archival_urls=(${{ github.event.inputs.urls }})
-        total_url_count=0
-        total_outlink_count=0
-
+        archival_urls=($(
+          IFS=$'\n'   # Set the Internal Field Separator to newline
+          echo "${{ github.event.inputs.urls }}" | sed -n '1,10p'
+        ))
         for url in "${archival_urls[@]}"; do
-
+          echo "Archiving given page: $url"
+    
           # Retry loop for the main content
           max_retries=3
           retry_counter=0
           while [ $retry_counter -lt $max_retries ]; do
-            if curl -sv "https://web.archive.org/save/$url" > /dev/null; then
+            if curl -sS "https://web.archive.org/save/$url" > /dev/null; then
               break
+            else
+              ((retry_counter++))
+              echo "Failed to archive main page: $url. Retrying..."
             fi
-            ((retry_counter++))
-          done || true  # Ignore errors
-
-          ((total_url_count++))
-
+          done
+      
           # Retry loop for outlinks
           curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
-
+            echo "Archiving outlink: $outlink"
+      
             max_retries=3
             retry_counter=0
             while [ $retry_counter -lt $max_retries ]; do
@@ -46,21 +44,242 @@ jobs:
                 break
               else
                 ((retry_counter++))
+                echo "Failed to archive outlink: $outlink. Retrying..."
               fi
             done
 
-            sleep 8s
-            ((total_outlink_count++))
-          done || true  # Ignore errors
+            sleep 6s
+          done || true  # Ignore errors in the outlink archiving process
 
-          sleep 8s
+          sleep 6s
         done
 
-        # Update total counts
-        current_url_count=$(<total_url_count.txt)
-        new_url_count=$((current_url_count + total_url_count))
+  archive_second_batch:
+    runs-on: ubuntu-latest
 
-        # Commit changes and push to origin
-        git add total_url_count.txt
-        git commit -m "Update total URL count"
-        git push origin
+    steps:
+    - name: Archive URLs (Second Batch)
+      run: |
+        archival_urls=($(
+          IFS=$'\n'   # Set the Internal Field Separator to newline
+          echo "${{ github.event.inputs.urls }}" | sed -n '11,20p'
+        ))
+        for url in "${archival_urls[@]}"; do
+          echo "Archiving given page: $url"
+    
+          # Retry loop for the main content
+          max_retries=3
+          retry_counter=0
+          while [ $retry_counter -lt $max_retries ]; do
+            if curl -sS "https://web.archive.org/save/$url" > /dev/null; then
+              break
+            else
+              ((retry_counter++))
+              echo "Failed to archive main page: $url. Retrying..."
+            fi
+          done
+      
+          # Retry loop for outlinks
+          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
+            echo "Archiving outlink: $outlink"
+      
+            max_retries=3
+            retry_counter=0
+            while [ $retry_counter -lt $max_retries ]; do
+              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
+                break
+              else
+                ((retry_counter++))
+                echo "Failed to archive outlink: $outlink. Retrying..."
+              fi
+            done
+
+            sleep 6s
+          done || true  # Ignore errors in the outlink archiving process
+
+          sleep 6s
+        done
+
+  archive_third_batch:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Archive URLs (Third Batch)
+      run: |
+        archival_urls=($(
+          IFS=$'\n'   # Set the Internal Field Separator to newline
+          echo "${{ github.event.inputs.urls }}" | sed -n '21,30p'
+        ))
+        for url in "${archival_urls[@]}"; do
+          echo "Archiving given page: $url"
+    
+          # Retry loop for the main content
+          max_retries=3
+          retry_counter=0
+          while [ $retry_counter -lt $max_retries ]; do
+            if curl -sS "https://web.archive.org/save/$url" > /dev/null; then
+              break
+            else
+              ((retry_counter++))
+              echo "Failed to archive main page: $url. Retrying..."
+            fi
+          done
+      
+          # Retry loop for outlinks
+          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
+            echo "Archiving outlink: $outlink"
+      
+            max_retries=3
+            retry_counter=0
+            while [ $retry_counter -lt $max_retries ]; do
+              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
+                break
+              else
+                ((retry_counter++))
+                echo "Failed to archive outlink: $outlink. Retrying..."
+              fi
+            done
+
+            sleep 6s
+          done || true  # Ignore errors in the outlink archiving process
+
+          sleep 6s
+        done
+
+  archive_fourth_batch:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Archive URLs (Fourth Batch)
+      run: |
+        archival_urls=($(
+          IFS=$'\n'   # Set the Internal Field Separator to newline
+          echo "${{ github.event.inputs.urls }}" | sed -n '31,40p'
+        ))
+        for url in "${archival_urls[@]}"; do
+          echo "Archiving given page: $url"
+    
+          # Retry loop for the main content
+          max_retries=3
+          retry_counter=0
+          while [ $retry_counter -lt $max_retries ]; do
+            if curl -sS "https://web.archive.org/save/$url" > /dev/null; then
+              break
+            else
+              ((retry_counter++))
+              echo "Failed to archive main page: $url. Retrying..."
+            fi
+          done
+      
+          # Retry loop for outlinks
+          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
+            echo "Archiving outlink: $outlink"
+      
+            max_retries=3
+            retry_counter=0
+            while [ $retry_counter -lt $max_retries ]; do
+              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
+                break
+              else
+                ((retry_counter++))
+                echo "Failed to archive outlink: $outlink. Retrying..."
+              fi
+            done
+
+            sleep 6s
+          done || true  # Ignore errors in the outlink archiving process
+
+          sleep 6s
+        done
+
+  archive_fifth_batch:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Archive URLs (Fifth Batch)
+      run: |
+        archival_urls=($(
+          IFS=$'\n'   # Set the Internal Field Separator to newline
+          echo "${{ github.event.inputs.urls }}" | sed -n '41,50p'
+        ))
+        for url in "${archival_urls[@]}"; do
+          echo "Archiving given page: $url"
+    
+          # Retry loop for the main content
+          max_retries=3
+          retry_counter=0
+          while [ $retry_counter -lt $max_retries ]; do
+            if curl -sS "https://web.archive.org/save/$url" > /dev/null; then
+              break
+            else
+              ((retry_counter++))
+              echo "Failed to archive main page: $url. Retrying..."
+            fi
+          done
+      
+          # Retry loop for outlinks
+          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
+            echo "Archiving outlink: $outlink"
+      
+            max_retries=3
+            retry_counter=0
+            while [ $retry_counter -lt $max_retries ]; do
+              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
+                break
+              else
+                ((retry_counter++))
+                echo "Failed to archive outlink: $outlink. Retrying..."
+              fi
+            done
+
+            sleep 6s
+          done || true  # Ignore errors in the outlink archiving process
+
+          sleep 6s
+        done
+
+  archive_sixth_batch:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Archive URLs (Sixth Batch)
+      run: |
+        archival_urls=($(
+          IFS=$'\n'   # Set the Internal Field Separator to newline
+          echo "${{ github.event.inputs.urls }}" | sed -n '51,60p'
+        ))
+        for url in "${archival_urls[@]}"; do
+          echo "Archiving given page: $url"
+    
+          # Retry loop for the main content
+          max_retries=3
+          retry_counter=0
+          while [ $retry_counter -lt $max_retries ]; do
+            if curl -sS "https://web.archive.org/save/$url" > /dev/null; then
+              break
+            else
+              ((retry_counter++))
+              echo "Failed to archive main page: $url. Retrying..."
+            fi
+          done
+      
+          # Retry loop for outlinks
+          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
+            echo "Archiving outlink: $outlink"
+      
+            max_retries=3
+            retry_counter=0
+            while [ $retry_counter -lt $max_retries ]; do
+              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
+                break
+              else
+                ((retry_counter++))
+                echo "Failed to archive outlink: $outlink. Retrying..."
+              fi
+            done
+
+            sleep 6s
+          done || true  # Ignore errors in the outlink archiving process
+
+          sleep 6s
+        done
